### ISSUE TITLE
[Open Source] Add share link to the Map Editor

### ISSUE THREAD

**Issue by cpojer** [nkzw-tech/athena-crisis#13]
For the Open Source website, it would be great if the [Map Editor Playground](http://athenacrisis.com/open-source/playground/map-editor) supported "saving" and loading maps. Let's store a map in the URL. When loading the playground, the URL can be decoded to load a map.

### Steps

* A callback for creating/updating a map can be passed to the component. When called, it should store the received data in the URL. In this case, the relevant use of the map editor is in [`map-editor.tsx`](https://github.com/nkzw-tech/athena-crisis/blob/main/docs/content/examples/map-editor.tsx#L19).
* If the data is present in the URL when loading the page, it should decode and pass it as `mapObject` to the `MapEditor` component.
  * Check out the definition of the [`MapObject`](https://github.com/nkzw-tech/athena-crisis/blob/main/hera/editor/Types.tsx#L91-L106).
* The create/update callbacks are called through the settings panel's "Save Map" button in the editor.

*Note: The Map Editor might not re-render with new state if the `mapObject` that gets passed in changes. It may be necessary to set the `key` prop to wipe away map editor state.

### Links

* [Map Editor Playground](http://athenacrisis.com/open-source/playground/map-editor)

### Funding

- We're using [Polar.sh](https://polar.sh/nkzw-tech) to distribute funds.
- You receive the reward once the issue is completed & confirmed by [Nakazawa Tech](https://nkzw.tech).

<a href="https://polar.sh/nkzw-tech/athena-crisis/issues/13">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/nkzw-tech/athena-crisis/issues/13/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/nkzw-tech/athena-crisis/issues/13/pledge.svg">
</picture>
</a>

**Comment by connorlindsey** [comment]
Super excited you're open sourcing so much of the game! Could I pick this issue up?

**Comment by cpojer** [comment]
Yes, please give it a try! Feel free to [ping me on the #tech channel on Discord](https://discord.gg/2VBCCep7Fk) if you have questions.

**Comment by connorlindsey** [comment]
Got a basic version working, but wanted to clarify how some of the `MapObject` properties should be handled, specifically:
- `id` - should this be auto-generated or just left as an empty string? From what I've read so far, I think an empty string would suffice
- `slug` - same as `id`
- `campaigns` - I'm assuming this should be empty (e.g. `campaigns: { edges: [] }`
- `creator` - I'm assuming we can use the placeholder `viewer` values

Thanks!

**Comment by cpojer** [comment]
For `slug`, please call [`toSlug`](https://github.com/nkzw-tech/athena-crisis/blob/main/hephaestus/toSlug.tsx) on the map name.

The other suggestions sound good to me.

I bumped up the funding to $50 since you are the first contributor.

**Comment by connorlindsey** [comment]
Thank you! Just excited to learn more about the codebase and making games with web tech, but that's super nice!

I set my PR as ready for review for when you're free to take a first pass. Obviously still getting used to the codebase, so let me know what feedback you have! Also let me know if you'd like me to include tests. Definitely can to be thorough and include them but I also feel like  it's not as necessary compared to something that updates the map editor, core unit logic, etc.

**Comment by cpojer** [comment]
Thanks for contributing, $50 were sent to you!

**Comment by connorlindsey** [comment]
Thanks! Appreciate the review and for open sourcing this 🎉
