### ISSUE TITLE
[Feature] Show Game Player Statistics during Gameplay

### ISSUE THREAD

**Issue by cpojer** [nkzw-tech/athena-crisis#2]
Right now there are no statistics to help players make better decisions. If a player wants to know how much funds each player is generating, or how many units each player has, they have to manually count them on the map. This task is a UI focused task to nicely present data available via the [`MapData`](https://github.com/nkzw-tech/athena-crisis/blob/main/athena/MapData.tsx) data structure. Most relevant information can be collected using helper functions such as [`calculateFunds`](https://github.com/nkzw-tech/athena-crisis/blob/main/athena/lib/calculateFunds.tsx).

Currently, player information is shown via [`CurrentGameCard`](https://github.com/nkzw-tech/athena-crisis/blob/main/hera/ui/CurrentGameCard.tsx). It expands when clicked:

https://github.com/nkzw-tech/athena-crisis/assets/13352/a138eef6-c109-4dc1-8271-1cacdcecb8ef

Ideally, this flyout receives the following information per player:
* Number of buildings
* Number of units
* Funds per turn
* ...?

### Notes
* *If fog is enabled on a map, it should only show visible information and/or show question marks given that the info may not be complete.*
* *This must work on small screens (iPhone) and large screens.*

### Funding

- We're using [Polar.sh](https://polar.sh/nkzw-tech) to distribute funds.
- You receive the reward once the issue is completed & confirmed by [Nakazawa Tech](https://nkzw.tech).

<a href="https://polar.sh/nkzw-tech/athena-crisis/issues/2">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/nkzw-tech/athena-crisis/issues/2/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/nkzw-tech/athena-crisis/issues/2/pledge.svg">
</picture>
</a>

**Comment by gillkyle** [comment]
Spent a bit this evening poking around the code and starting to hack at rendering some of this data over on my fork: https://github.com/gillkyle/athena-crisis/tree/current-game-card

Been using the docs pages to render a playground game where I'm rendering the `CurrentGameCard` to test some changes. Was familiarizing myself with some of the pieces of game state in the process, trying to identify if there are other bits of data that might render in other cases (like player skills it seems?..). 

![CleanShot 2024-05-14 at 21 48 50@2x](https://github.com/nkzw-tech/athena-crisis/assets/21114044/8aed4437-808d-49b5-9b94-5930ad877400)

Probably several better ways to compress this data into the small available space, like showing some data only when expanded. 

I'm gaving fun, but can't guarantee I'll be able to keep moving it forward super fast (so if anyone else sees this feel free to jump in).

**Comment by cpojer** [comment]
Thanks for trying to build it! Seems like @sookmax sent a PR first: https://github.com/nkzw-tech/athena-crisis/pull/23

**Comment by cpojer** [comment]
Implemented by @sookmax.
