### ISSUE TITLE
Can reinforcement learning be used to develop AI for this game?

### ISSUE THREAD

**Issue by allendred** [nkzw-tech/athena-crisis#30]
I'm interested in exploring the possibility of using reinforcement learning (RL) to develop the AI for this game. I want to know whether RL is a suitable approach for it.

 questions:

Has anyone tried using reinforcement learning for developing AI for this game?
What are the potential challenges and limitations of using RL for this purpose?

Any insights, experiences, or resources related to using RL for this game AI development would be highly appreciated.

**Comment by cpojer** [comment]
I don't think it has been tried yet, but I'm sure it's possible. Athena Crisis, at its core, is similar to chess. However, it is more complex so building a good model likely requires intense training and compute. I would suggest starting out with a small map, recording game actions, and teaching things step by step and growing from there.

**Comment by cpojer** [comment]
Closing this since it is not an "Issue", this should be moved to "Discussions" if you'd like to keep the conversation going.
