### ISSUE TITLE
Error when starting Gamer via Steam on Windows

### ISSUE THREAD

**Issue by lcatania** [nkzw-tech/athena-crisis#51]
Hey,

i got a key to try the game but everytime i try to start the game i get a module not found error.

I hope someone can help me. Thank you <3

![image](https://github.com/user-attachments/assets/84d68403-fa31-4717-933d-b384015fd9f8)

**Comment by lcatania** [comment]
This are my specs 

![image](https://github.com/user-attachments/assets/82b94742-e3d0-4589-9f87-72d0fa3c9a1c)
![image](https://github.com/user-attachments/assets/6e76cfda-0ba8-45a3-a5cc-63f2590e7808)

**Comment by cpojer** [comment]
Thanks for reporting. I will investigate and hopefully fix it, it looks like it doesn't run on older hardware.

The app part of Athena Crisis is not open source, so I'll close this issue here.

**Comment by cpojer** [comment]
Update: There seems to have been a missing system file which Athena Crisis depends on. Restoring that file fixed the issue.
