### ISSUE TITLE
Intro State not persisted

### ISSUE THREAD

**Issue by lcatania** [nkzw-tech/athena-crisis#54]
When inspecting a unit and going to the damage table overview you can't go back and resume the scenario you have to go through all the dialogs again.

Maybe a skip dialog would be good or some sort of state that is kept in memory.

**Comment by cpojer** [comment]
This will be fixed this week. The goal was to ship the tutorial this week.

(This code is not open source, so will close the issue here but it is managed in a separate tracker).
